# Generated by Django 5.1.15 on 2026-05-27 06:44

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='IngestionJob',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('source_type', models.CharField(choices=[('sap', 'SAP (Fuel / Procurement)'), ('utility', 'Utility (Electricity)'), ('travel', 'Corporate Travel')], max_length=10)),
                ('file_name', models.CharField(max_length=500)),
                ('file', models.FileField(upload_to='uploads/csv/%Y/%m/')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('total_rows', models.PositiveIntegerField(default=0)),
                ('valid_rows', models.PositiveIntegerField(default=0)),
                ('error_rows', models.PositiveIntegerField(default=0)),
                ('duplicate_rows', models.PositiveIntegerField(default=0)),
                ('processing_errors', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingestion_jobs', to='core.tenant')),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ingestion_jobs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SAPRawRow',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('row_number', models.PositiveIntegerField(help_text='1-based row index in the CSV')),
                ('raw_data', models.JSONField(help_text='The entire original CSV row as key-value pairs.')),
                ('is_valid', models.BooleanField(default=True)),
                ('is_duplicate', models.BooleanField(default=False)),
                ('validation_errors', models.JSONField(blank=True, default=list, help_text='List of {type, field, message} dicts.')),
                ('row_hash', models.CharField(blank=True, db_index=True, help_text='SHA-256 of key fields for duplicate detection.', max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('document_number', models.CharField(blank=True, max_length=50)),
                ('movement_type', models.CharField(blank=True, max_length=10)),
                ('material_number', models.CharField(blank=True, max_length=50)),
                ('plant_code', models.CharField(blank=True, max_length=10)),
                ('quantity', models.DecimalField(blank=True, decimal_places=4, max_digits=18, null=True)),
                ('unit_of_measure', models.CharField(blank=True, max_length=10)),
                ('posting_date', models.DateField(blank=True, null=True)),
                ('currency', models.CharField(blank=True, max_length=5)),
                ('amount_local', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_rows', to='ingestion.ingestionjob')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.tenant')),
            ],
            options={
                'ordering': ['row_number'],
                'indexes': [models.Index(fields=['job', 'row_number'], name='ingestion_s_job_id_8ea39f_idx')],
            },
        ),
        migrations.CreateModel(
            name='TravelRawRow',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('row_number', models.PositiveIntegerField(help_text='1-based row index in the CSV')),
                ('raw_data', models.JSONField(help_text='The entire original CSV row as key-value pairs.')),
                ('is_valid', models.BooleanField(default=True)),
                ('is_duplicate', models.BooleanField(default=False)),
                ('validation_errors', models.JSONField(blank=True, default=list, help_text='List of {type, field, message} dicts.')),
                ('row_hash', models.CharField(blank=True, db_index=True, help_text='SHA-256 of key fields for duplicate detection.', max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('trip_id', models.CharField(blank=True, max_length=50)),
                ('employee_id', models.CharField(blank=True, max_length=50)),
                ('travel_date', models.DateField(blank=True, null=True)),
                ('origin_iata', models.CharField(blank=True, max_length=5)),
                ('destination_iata', models.CharField(blank=True, max_length=5)),
                ('travel_class', models.CharField(blank=True, max_length=30)),
                ('trip_type', models.CharField(blank=True, help_text='one_way or round_trip', max_length=20)),
                ('distance_km', models.DecimalField(blank=True, decimal_places=2, help_text='Great-circle distance; computed if IATA codes present.', max_digits=12, null=True)),
                ('transport_mode', models.CharField(blank=True, default='air', help_text='air, rail, road, etc.', max_length=30)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_rows', to='ingestion.ingestionjob')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.tenant')),
            ],
            options={
                'ordering': ['row_number'],
                'indexes': [models.Index(fields=['job', 'row_number'], name='ingestion_t_job_id_1c51b3_idx')],
            },
        ),
        migrations.CreateModel(
            name='UtilityRawRow',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('row_number', models.PositiveIntegerField(help_text='1-based row index in the CSV')),
                ('raw_data', models.JSONField(help_text='The entire original CSV row as key-value pairs.')),
                ('is_valid', models.BooleanField(default=True)),
                ('is_duplicate', models.BooleanField(default=False)),
                ('validation_errors', models.JSONField(blank=True, default=list, help_text='List of {type, field, message} dicts.')),
                ('row_hash', models.CharField(blank=True, db_index=True, help_text='SHA-256 of key fields for duplicate detection.', max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('meter_id', models.CharField(blank=True, max_length=50)),
                ('facility_name', models.CharField(blank=True, max_length=255)),
                ('billing_start', models.DateField(blank=True, null=True)),
                ('billing_end', models.DateField(blank=True, null=True)),
                ('consumption_kwh', models.DecimalField(blank=True, decimal_places=4, max_digits=18, null=True)),
                ('unit', models.CharField(blank=True, default='kWh', max_length=20)),
                ('cost', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('currency', models.CharField(blank=True, max_length=5)),
                ('provider', models.CharField(blank=True, max_length=255)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_rows', to='ingestion.ingestionjob')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.tenant')),
            ],
            options={
                'ordering': ['row_number'],
                'indexes': [models.Index(fields=['job', 'row_number'], name='ingestion_u_job_id_18f8ca_idx')],
            },
        ),
    ]
