# Generated by Django 5.1.15 on 2026-05-27 06:44

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmissionRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('source_type', models.CharField(max_length=10)),
                ('source_row_id', models.UUIDField(blank=True, help_text='PK of the raw row that produced this record.', null=True)),
                ('scope', models.CharField(choices=[('scope_1', 'Scope 1 — Direct'), ('scope_2', 'Scope 2 — Indirect (Energy)'), ('scope_3', 'Scope 3 — Value Chain')], max_length=10)),
                ('scope_category', models.CharField(blank=True, help_text="Sub-category, e.g. 'Scope 3 Cat 6 — Business Travel'", max_length=100)),
                ('activity_type', models.CharField(help_text="e.g. 'Diesel Combustion', 'Grid Electricity', 'Air Travel'", max_length=100)),
                ('facility', models.CharField(blank=True, max_length=255)),
                ('activity_amount', models.DecimalField(decimal_places=4, help_text='Quantity in the original unit (litres, kWh, km, etc.)', max_digits=18)),
                ('activity_unit', models.CharField(max_length=30)),
                ('emission_factor_id', models.UUIDField(blank=True, help_text='FK to EmissionFactor used (stored as UUID for flexibility).', null=True)),
                ('emission_factor_value', models.DecimalField(blank=True, decimal_places=6, help_text='Snapshot of the factor at computation time.', max_digits=12, null=True)),
                ('co2e_kg', models.DecimalField(decimal_places=4, help_text='Computed CO₂e in kilograms.', max_digits=18)),
                ('record_date', models.DateField(help_text='The date the underlying activity occurred.')),
                ('reporting_period', models.CharField(blank=True, help_text='YYYY-MM format for aggregation.', max_length=7)),
                ('status', models.CharField(choices=[('pending', 'Pending Review'), ('reviewed', 'Reviewed'), ('approved', 'Approved'), ('flagged', 'Flagged'), ('locked', 'Locked')], default='pending', max_length=10)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('flag_reason', models.TextField(blank=True)),
                ('scope_override', models.CharField(blank=True, help_text='Analyst-overridden scope (with audit trail).', max_length=10)),
                ('override_reason', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-record_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PlantCodeMapping',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('plant_code', models.CharField(max_length=10)),
                ('facility_name', models.CharField(max_length=255)),
                ('location', models.CharField(blank=True, max_length=255)),
                ('country', models.CharField(blank=True, max_length=100)),
            ],
            options={
                'ordering': ['plant_code'],
            },
        ),
        migrations.CreateModel(
            name='EmissionFactor',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('category', models.CharField(choices=[('fuel', 'Fuel Combustion'), ('electricity', 'Electricity Grid'), ('travel_air', 'Air Travel'), ('travel_rail', 'Rail Travel'), ('travel_road', 'Road Travel')], max_length=30)),
                ('name', models.CharField(help_text="e.g. 'Diesel', 'Natural Gas', 'US Grid Average', 'Air Economy'", max_length=255)),
                ('unit', models.CharField(help_text="Input unit, e.g. 'L', 'kWh', 'km'", max_length=30)),
                ('factor_kg_co2e', models.DecimalField(decimal_places=6, help_text='kg CO₂e per one unit', max_digits=12)),
                ('source', models.CharField(blank=True, default='EPA', help_text='EPA, DEFRA, custom, etc.', max_length=50)),
                ('year', models.PositiveSmallIntegerField(default=2024, help_text='Reference year for the factor.')),
                ('region', models.CharField(blank=True, default='Global', help_text='Geographical applicability.', max_length=100)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['category', 'name'],
                'unique_together': {('category', 'name', 'unit', 'year', 'region')},
            },
        ),
    ]
