# Generated by Django 5.1.15 on 2026-05-27 06:44

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(choices=[('create', 'Create'), ('update', 'Update'), ('delete', 'Delete'), ('status_change', 'Status Change'), ('approve', 'Approve'), ('reject', 'Reject'), ('flag', 'Flag'), ('lock', 'Lock'), ('upload', 'Upload')], max_length=20)),
                ('entity_type', models.CharField(help_text="App label + model name, e.g. 'emissions.EmissionRecord'", max_length=100)),
                ('entity_id', models.CharField(help_text='PK of the affected object (stringified UUID).', max_length=255)),
                ('changes', models.JSONField(blank=True, default=dict, help_text='JSON diff: {field: {old: ..., new: ...}}')),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Arbitrary extra context (e.g. reason for flagging).')),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to='core.tenant')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['entity_type', 'entity_id'], name='audit_audit_entity__9535bf_idx'), models.Index(fields=['tenant', 'timestamp'], name='audit_audit_tenant__7e6e1d_idx')],
            },
        ),
    ]
